version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - "POSTGRES_DB:${POSTGRES_DB}"
      - "POSTGRES_USER:${POSTGRES_USER}"
      - "POSTGRES_PASSWORD:${POSTGRES_PASSWORD}"
  web:
    build: ./backend/pizza-app
    command: >
      sh -c "python pizza/manage.py migrate &&
             python pizza/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/pizza-app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
