# Generated by Django 3.2.7 on 2021-09-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='user',
            field=models.TextField(default=None, help_text='Author of pizza', max_length=64),
            preserve_default=False,
        ),
    ]
